apiVersion: v1
kind: Service
metadata:
  labels:
    appName: wine-quality-ml-machine-learning-model
  name: wine-quality-ml-machine-learning-model
spec:
  selector:
    app: wine-quality-ml-machine-learning-model
  ports:
    - name: "management"
      port: 8558
      protocol: TCP
      targetPort: 8558
---
#
# Create a role, `pod-reader`, that can list pods and
# bind the default service account in the `default` namespace
# to that role.
#

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
  - kind: User
    name: system:serviceaccount:wine-quality-ml:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io