apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfserving
  namespace: {{ .Values.application }}
  labels:
    app: tfserving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfserving
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tfserving
    spec:
      containers:
        - name: serving
          image: "{{ .Values.image.server }}:{{ .Values.image.version }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 8501
              name: serving
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: serving
            initialDelaySeconds: 15
            timeoutSeconds: 1
          env:
            - name: "AWS_REGION"
              value: "eu-west-1"
            - name: "S3_REGION"
              value: "eu-west-1"
            - name: "S3_ENDPOINT"
              value: "s3.eu-west-1.amazonaws.com"
            - name: "S3_USE_HTTPS"
              value: "1"
            - name: "S3_VERIFY_SSL"
              value: "1"
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom: { secretKeyRef: { name: "awsaccess", key: "AWS_ACCESS_KEY_ID" } }
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom: { secretKeyRef: { name: "awsaccess", key: "AWS_SECRET_ACCESS_KEY" } }
            - name: "MODEL_BASE_PATH"
              value: "s3://fdp-killrweather-data/kubeflow/recommeder/model"
            - name: "MODEL_NAME"
              value: "recommender"




          volumes:
            - name: secret-volume
              secret:
                secretName: awsaccess
---
apiVersion: v1
kind: Service
metadata:
  name: tfserving
  namespace: {{ .Values.application }}
spec:
  selector:
    app: tfserving
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501

